spring.application.name=myfirstwebapp

#server.port=8081

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

logging.level.org.springframework=info
logging.level.com.in23minutes.springboot.myfirstwebapp=info

spring.mvc.format.date=yyyy-MM-dd

spring.h2.console.enabled=true
# This sets the URL to /h2-console
spring.h2.console.path=/h2-console
# This ensures your DB name doesn't change every time you restart
spring.datasource.url=jdbc:h2:mem:testdb